apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  labels:
    example.cloud/part-of: gateway 
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: PersistentVolume
  sourceRepos:
  - https://github.com/cliffpracht/test-repo
  syncWindows: []
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project2
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: PersistentVolume
  sourceRepos:
  - https://github.com/cliffpracht/test-repo
  syncWindows: []
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
