apiVersion: v1
data:
  globalProjects: |-
    - labelSelector:
        matchExpressions:
          - key: example
            operator: In
            values:
              - gateway
      projectName: proj-global-test
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
