apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: identity-management
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: PersistentVolume
  sourceRepos:
  - https://github.com/cliffpracht/test-repo
  syncWindows: []
