apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: origin
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - project: project1
  template:
    metadata:
      name: "{{project}}-applicationsets"
    spec:
      project: project1
      source:
        repoURL: https://github.com/cliffpracht/test-repo
        targetRevision: HEAD
        path: "app-set/{{project}}"
      destination:
        namespace: argocd
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=false
