apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-eks-system
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: service1
                  namespace: ns1
                  overlay: overlays/default
                - service: service2
                  namespace: ns2
                  overlay: overlays/default
          - clusters: {}
    - merge:
        generators:
           - list:
              elements:
                - cluster: 'https://kubernetes.docker.internal:6443'
                  service: servicexxx
                  namespace: ns1
                  overlay: new
  template:
    # {{.name}} and {{.server}} provided by cluster generator
    metadata:
      name: '{{printf "%s-aws-eks-system-%s" .name .service | printf "%.63s"}}'
      labels:
        app: "{{.service}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/cliffpracht/test-repo
        targetRevision: HEAD
        path: 'service/{{.service}}/{{default "base" .overlay}}'
      destination:
        server: "{{.server}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace={{default false .createNamespace}}
